# Generated by Django 5.0.6 on 2024-07-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_person_team_person_team_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="team_name",
        ),
        migrations.AddField(
            model_name="person",
            name="team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="home.team",
                to_field="team_name",
            ),
        ),
    ]
