# Generated by Django 5.0.6 on 2024-07-08 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_team_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="home.team",
                to_field="team_name",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
